### ISSUE TITLE
Implement logging plugin

### ISSUE THREAD

**Issue by Marak** [nodejitsu/kohai#1]
We should be able to log the IRC channel which Kohai is present in.

We should use a standard IRC logging format. Log files should be separated by date.

**Comment by mandric** [comment]
+1 ;)

**Comment by Marak** [comment]
TODO:
1. Clean up format of logging data ( use standard IRC formats, provide multiple options )
2. Patch Winston to allow for date / time spans of the File transport ( see: https://github.com/indexzero/winston/issues/10 )

**Comment by AvianFlu** [comment]
http://github.com/AvianFlu/kohai-logger
