### ISSUE TITLE
Auto-Promote

### ISSUE THREAD

**Issue by heapwolf** [nodejitsu/kohai#12]
Im not sure if this is the responsibility of kohai, but it would be very useful to have a bot automatically promote the co-founders to ops and give voice to our crew.

**Comment by heapwolf** [comment]
duplicate of issue 15 (Even though this ticket came first, 15 has a better description).

**Comment by AvianFlu** [comment]
Good idea.  Prerequisite tickets:

https://github.com/nodejitsu/kohai/issues/14 - give kohai ability to run commands after identifying

https://github.com/nodejitsu/kohai/issues/15 - commands on user part/join

**Comment by Marak** [comment]
Re-opened ticket. This ticket is separate functionality from #14 and #15. Once we get those two done, this ticket can be done.

**Comment by AvianFlu** [comment]
Kohai will now auto-op, auto-voice, and auto-ban based on the lists in config.json.
