### ISSUE TITLE
Kohai twitter auto-follow functionality

### ISSUE THREAD

**Issue by AvianFlu** [nodejitsu/kohai#18]
Kohai should auto-follow everyone who tweets about related topics.

**Comment by AvianFlu** [comment]
While the Twitter API supports this, the current version of node-twitter does not appear to.  May need to hold off on this.

**Comment by Marak** [comment]
You could always patch node-twitter then submit a pull request. While waiting for the author to pull / merge you can add your own fork as a vendor dep.

**Comment by AvianFlu** [comment]
It's true - the twitter API isn't exactly rocket science.  I'll look into it.

**Comment by AvianFlu** [comment]
Upon further investigation, node-twitter definitely supports this.  This shouldn't be any trouble.

**Comment by AvianFlu** [comment]
It turns out that having kohai follow people leads to a ton of excess tweets.  Closing issue.

**Comment by Marak** [comment]
That is unrelated to functionality. 

Why can we just have Kohai not automatically broadcast the tweets of people he is following?

**Comment by AvianFlu** [comment]
The issue with tweeting follower messages has been solved, but it depends on a patch to @jdub 's node-twitter ( https://github.com/jdub/node-twitter/pull/16 ) to support the relevant method in the Twitter Stream API. The auto-follow functionality itself should be trivial to add.

**Comment by AvianFlu** [comment]
Can be configured with `!config set plugins:irc:twitter:autofollow "true"|"false"`
