### ISSUE TITLE
Implement aliases plugin

### ISSUE THREAD

**Issue by Marak** [nodejitsu/kohai#2]
We should be able to define triggers in a specific file so we can easily create aliases / additional triggers which do not require a separate plugin.

**Comment by AvianFlu** [comment]
There's some code that does this already in server.js, lines 17-26... the hash is just empty as-is.  I added a test trigger and everything works.  Should it be moved to its own module, or left alone?

**Comment by AvianFlu** [comment]
Nevermind prior comment.  Module implemented, new triggers go in the hash as "name" : function(data) {callback} , and get accessed with !trigger from chat as expected.  Closing issue.
