### ISSUE TITLE
Add shortlink after each Tweet announcement in IRC

### ISSUE THREAD

**Issue by Marak** [nodejitsu/kohai#20]
Everytime a twitter message gets piped to IRC, we should include a shortlink ( perhaps bit.ly ) that provides a link to the original tweet. 

This will allow IRC users to click on the link and be brought to the Tweet, should they wish to interact with it via Twitter.com instead of the IRC channel.

**Comment by AvianFlu** [comment]
This seems relevant.  https://github.com/tanepiper/node-bitly

**Comment by Marak** [comment]
1. Add node-bitly as a plugin
2. Make freenode plugin use bitly plugin API
