### ISSUE TITLE
Configurable command string

### ISSUE THREAD

**Issue by affinity-matrix** [nodejitsu/kohai#21]
Kohai should have a configurable command string/character, to prevent it from clashing with other potential bots that use the default "!" command character.

edit: bmeck's suggestion.

**Comment by bmeck** [comment]
Might want it to be a string explicitly instead of character, some
bots use things like 'js:' and 'v8 '

On Wed, May 18, 2011 at 2:22 PM, emilyrose
reply@reply.github.com
wrote:

**Comment by AvianFlu** [comment]
This is a good idea generally and super-helpful for testing purposes.  Thanks for the idea - closing issue.
