### ISSUE TITLE
Implement levenshtein algo to help better detect retweets for Twitter plugin

### ISSUE THREAD

**Issue by Marak** [nodejitsu/kohai#22]
https://github.com/gf3/Levenshtein/blob/master/lib/levenshtein.js 

or

https://gist.github.com/979790

I'd opt for @gf3 's library, since if it doesn't work it will be more fun to yell at him.

**Comment by AvianFlu** [comment]
We could also use Levenshtein to catch questions asked in IRC and compare them to an FAQ or something similar, then pipe back or link the response.
