### ISSUE TITLE
Announce Git commits to IRC

### ISSUE THREAD

**Issue by heapwolf** [nodejitsu/kohai#26]
kohai should be able to stream in Git commit messages from github projects to the IRC room.

**Comment by mscdex** [comment]
Can't this already be done with github's commit hook IRC bot?

**Comment by jfhbrook** [comment]
I've implemented a git-watching irc plugin like four times for browserling. I plan to do a fifth refactor Any Day Now. I'd be glad to rewrite it with Kohai in mind. ^__^

**Comment by jfhbrook** [comment]
@mscdex one nice thing about an irc bot would be that you could choose which to watch from "your side" instead of having to get the repo owner to "point" their repo to your bot. I actually tried a non-polling approach previously, and culturally it just don't work.

**Comment by mscdex** [comment]
@jesusabdullah wouldn't you have to poll github's api to detect new commits, or do they have a stream api now? How common would it be that you'd want to be monitoring commits for a repo you don't own over IRC?

**Comment by jfhbrook** [comment]
Addendum: Other information from github would also be useful, such as changes in issues, updates in # watched, etc.

**Comment by jfhbrook** [comment]
@mscdex First: Yes, you do have to poll the API every few seconds. They're working on a v3 api now but I believe it's also non-streaming (if it were that'd be radtastic). As far as monitoring commits you don't own: It happens pretty often actually.

Here's an example that has probably happened irl: I wrote my IRC bot and wanted it to get updates on /substack/dnode, which is part of the browserling stack. However, it's SubStack's repo, so I'd have to explain to/remind him to point his repo to send messages to the IRC bot.

Or, alternately, I could add dnode to a json-based config myself. Yes it's polling, but culturally it's easier.

**Comment by Marak** [comment]
@jesusabdullah - Is there any status on this? Do you have something online we can look at?

Thanks!

**Comment by jfhbrook** [comment]
@marak Yeah, kind of. I have an old codebase I need to get around to refactoring.

https://github.com/jesusabdullah/lulzbot/tree/master/gitwatch is the old gitwatch code. It's kind of a mess right now, unfortunately.

**Comment by AvianFlu** [comment]
This is now taken care of by github's service hooks.  Closing issue.
