### ISSUE TITLE
Parse html entities

### ISSUE THREAD

**Issue by affinity-matrix** [nodejitsu/kohai#28]
Kohai does not parse html entities. I think it should, no?

`&gt;, &lt;, etc...`

**Comment by Marak** [comment]
Can you be more specific?

**Comment by affinity-matrix** [comment]
e.g.

<kohai> @mikespokefire: Today's task is to conquer Rails `:remote =&gt;` true and to install node.js

**Comment by Marak** [comment]
Ahh, it should be a trivial fix. I'm not sure where the actual escaping is happening though.

**Comment by affinity-matrix** [comment]
On twitter.

**Comment by bmeck** [comment]
https://github.com/bmeck/jsentities
require('JS-Entities').html.[en,de]code(...) ?

Should this be optional?

On Sat, May 21, 2011 at 7:40 AM, emilyrose
reply@reply.github.com
wrote:

**Comment by affinity-matrix** [comment]
I'm not sure that it's really necessary to worry about much more than `&lt;, &gt;`. From what I've seen, twitter doesn't escape that which can't be used for injection (and it didn't even do that for a time).
