### ISSUE TITLE
Expose plugins on the `kohai` object

### ISSUE THREAD

**Issue by indexzero** [nodejitsu/kohai#31]
Plugins are not available directly on the `kohai` object right now. This will make it impossible to start/stop plugins in process. This should be modelled after the plugin system in haibu:

https://github.com/nodejitsu/haibu/blob/master/lib/haibu.js#L62

**Comment by Marak** [comment]
+1 @AvianFlu

**Comment by AvianFlu** [comment]
The way plugins load has been changed to more closely parallel the method used in haibu.  Plugins will now be loaded upon dropping them into lib/plugins and starting the bot.
