### ISSUE TITLE
Create !help command

### ISSUE THREAD

**Issue by AvianFlu** [nodejitsu/kohai#32]
Kohai should have a trigger to return a list of triggers, and possibly short explanations of their purposes.

**Comment by DTrejo** [comment]
+1

link to github / readme would also be cool

**Comment by Marak** [comment]
I think considering the amount of commands, it would be most appropriate for `kohai` to PM the user who hit the `!help` trigger.

**Comment by AvianFlu** [comment]
lib/plugins/help.js has been added, which implements a !help command.  Once the dnode refactor has been completed, a better help system can be implemented... but this should carry us through the experimental phase at least.

**Comment by DTrejo** [comment]
Nice. Just used it and I like it a lot.

On Thu, Jun 2, 2011 at 11:01 PM, AvianFlu <
reply@reply.github.com>wrote:

> lib/plugins/help.js has been added, which implements a !help command.  Once
> the dnode refactor has been completed, a better help system can be
> implemented... but this should carry us through the experimental phase at
> least.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/nodejitsu/kohai/issues/32#comment_1289962

## 

My indie music project, mixest.com
for more projects, dtrejo.com
