### ISSUE TITLE
twitter streaming is overly noisy

### ISSUE THREAD

**Issue by isaacs** [nodejitsu/kohai#39]
It would be good if kohai only fed in tweet mentions if there has been no other activity in the room for 60 seconds, and no more than once per 30 second interval.

It can get really noisy and distracting at times, but it is nice to have that connection to twitter, and to stimulate activity when nothing else is going on.

**Comment by Marak** [comment]
The whole point of intercepting real-time data is to not rate-limit or drop messages. Any dropped messages defeat the entire purpose of the thing.

Currently there is the `!mute` and `!unmute` commands which will silence the bot as per the configurable interval. ( this can all be done via IRC by whitelisted users, which can also be added / removed from IRC )

Are these enough to silence the bot during times of discussion?

**Comment by Marak** [comment]
Also, there was a bug where kohai was retweeting any messages of users it was following. 

This was causing an extreme excess of messages. We've unfollowed everyone from the NodeKohai account, so this won't happen anymore.

**Comment by isaacs** [comment]
If you want to see every mention of #node on twitter, set up a search in your twitter client.

> Are these enough to silence the bot during times of discussion?

No, it is not.  My request is for Kohai to behave reasonably by default.  If we have to !mute it every time we want to use the room during US daylight hours, then it defeats the purpose.

**Comment by Marak** [comment]
I'm taking the bot down until further notice. I don't need the aggravation this is causing me today. 

We've pulled in close to 10 people this week to the IRC room who were having difficulties with Node that got the support they needed. These people would not have gotten any support if it were not for the bot. 

One person following hash tags doesn't do shit. You need to have the community actively engaging with each other. You pull in one person via kohai and help them, they will do the same for two more people, and so on. 

The value in doing this is immeasurable. If you'd rather have the onus of node.js support be on individual people opposed to the community, you've setup a framework that severely limits the amount of real-time support that can be provided.

**Comment by isaacs** [comment]
That's why the initial request was for Kohai to stream twitter in a not-annoying manner, rather than not at all.

**Comment by AvianFlu** [comment]
This is a very early version of kohai still, and the periods of time spent in the #Node.js room have been very valuable in terms of testing and feedback so far.  It seems to me that the most logical course of action would be to have kohai make periodic visits for testing-by-fire, if you will, but not be a permanent resident until he's quieter/more mature/whatever.  

A separate room for people who want to answer questions via kohai tweets might also not be a bad idea.

**Comment by Marak** [comment]
@AvianFlu - I think both of those suggestions are pretty reasonable actually. We should open up a support room.

**Comment by Marak** [comment]
I'm closing this ticket and have created two follow up tickets based on this discussion.

https://github.com/nodejitsu/kohai/issues/40
https://github.com/nodejitsu/kohai/issues/41

**Comment by Marak** [comment]
Both follow up tickets have been closed. Issue should be solved...
