### ISSUE TITLE
Add ability to manage configuration settings per plugin / split up config.json

### ISSUE THREAD

**Issue by Marak** [nodejitsu/kohai#49]
We should break out the individual plugin configurations in the main config.json and have them set on the plugin level instead.

**Comment by chapel** [comment]
e.g. having their own config.json file?

I think this would be good, would allow for more robust and complicated plugins without polluting the main config.

**Comment by Marak** [comment]
My thoughts exactly. This is probably something we'd want to implement in the plugin constructor.
