### ISSUE TITLE
commands for displaying common info

### ISSUE THREAD

**Issue by heapwolf** [nodejitsu/kohai#61]
kohai should report open bugs and places to go for help when particular keywords are mentioned.

**Comment by AvianFlu** [comment]
This is a good idea.  There are a few ways we could do it, though.

The easy way would be to keep a continuously-updated key-value list where keywords have responses as values.  This would be updated to reflect whatever issues are common at the moment.  Development time would be negligible, but maintaining the data would be more of a pain over time.

The not-so-easy way:
- regex for sentences that are questions. `/.+\?+(?:\s*.*\?*|$)/` would be one basic way to test.
- split on space, levenshtein match against a list of keywords to allow for bad spelling, choose a few 'tags' for the question.
- pick one or two things to link based on the estimated tag relevance.  This could involve GitHub API integration, a kohai account on the node.js mailing list, our assistly knowledge base, or just about anything else.

There would be more development time for the latter, but less pain over time.  I'll start to experiment with the matching side of this, and I'll see what I can put together.

**Comment by heapwolf** [comment]
we could start with something less intelegent...

```
  <hij1nx>!help
  kohai:[HELP] !bug <bug id> : Look up a bug on issues.nodejitsu.com
  kohai:[HELP] bz://<bug id> : Look up a bug on issues.nodejitsu.com
  kohai:[HELP] !bugsearch <terms> : Do a search for bugs on issues.nodejitsu.com
  kohai:[HELP] !wiki <terms> : Finds wiki pages that have terms in the title
  kohai:[HELP] !pull <repository> <terms?> : Find pull-requests on a nodejitsu repository
  kohai:[HELP] !kb <terms> : Search the Knowledge Base on help.nodejitsu.com
  kohai:[HELP] !vimeo <terms> : Search nodejitsu's videos (also !video and !webinar)
```

**Comment by AvianFlu** [comment]
Many of these have been implemented, and new ones can be added on the fly.
